name: Tests

on:
  push:
    branches:
      - dev
      - master

jobs:
  hello-world:
    runs-on: ubuntu-20.04

    steps:
    - name: print hello
      shell: bash
      run: echo Welcome to the Github Actions workshop !
  unit-tests:
    runs-on: ubuntu-20.04

    steps:
    - name: check repo
      uses: action/checkout@workshop-ga-Nekory23
      with:
        ref: dev

    - name: run unit-tests
      run: make tests_run

    - name: run coverage
      run: make coverage