name: Tests

on:
  push:
    branches:
      - dev
      - master

jobs:
  hello-world:
    runs-on: ubuntu-20.04

    steps:
    - name: print hello
      shell: bash
      run: echo Welcome to the Github Actions workshop !
  unit-tests:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run unit-tests
      shell: bash
      run: make tests_run

    - name: Run coverage
      shell: bash
      run: make coverage